### PR TITLE
Update Package.swift

### PR DESCRIPTION
**Pull request by gbreen12**
This fixes SPM

### CODE REVIEW

**Comment by ole** [comment]
@gbreen12 Thank you for this! It may take me a few days to take a look at this.

**Comment by gbreen12** [comment]
No problem! All it does is exclude the ReadMe.md files from each folder so not much going on there. Alternatively we could add an `include` I think but I don't know that it matter either way really

**Comment by ole** [comment]
@gbreen12 Sorry again for taking so much time to respond. I looked at this just now and I'm wondering what you mean by "this *fixes* SPM". I.e., in what way is SPM support broken for you?

I can run `swift build` and `swift test` just fine with a current Swift 5.3 toolchain (on macOS). I can also successfully use the Ampere package as a dependency in another package.

**Comment by gbreen12** [comment]
Hmm so I am able to use the master branch but not the 0.4.0 release.

Here is a video of me trying to use it in a branch new project.

https://youtu.be/6LAmZWaUayA

**Comment by ole** [comment]
Thanks for the video. I think I found the problem: SwiftPM seems to expect a tag named "0.4.0" but the tag in the repository was named "0.4". I just added the "0.4.0" tag and now it seems to work without any code changes. I don't know if older SwiftPM versions behaved differently or not.

I'm going to merge your PR, but I don't think the missing `exclude`s were the reason for the package resolution problems. Thanks again for your patience with me.

**Comment by ole** [comment]
A also made a new release, 0.4.1 (though as I said I don't think it's strictly necessary).

**Comment by gbreen12** [comment]
Great thanks for that!

**Pull request merged**
